### ISSUE TITLE
AWS account key and secret key

### ISSUE THREAD

**Issue by ghost** [lorieri/zabbix#2]
Where is the account keys are configured (manually) to allow connection between Zabbix and Cloudwatch?

**Comment by lorieri** [comment]
Hi,

it is so old ...

it is in this file:
https://github.com/lorieri/zabbix/blob/af4e8d81b71cf743ef3ecb3abf6837f9c66280f2/chef/cookbooks/zabbix-aws/templates/default/cloudwatch/zabbix-cloudwatch.py.erb#L43


it uses chef to configure
the attribute files is this one:
https://github.com/lorieri/zabbix/blob/af4e8d81b71cf743ef3ecb3abf6837f9c66280f2/chef/cookbooks/zabbix-aws/attributes/zabbix_aws_defaults.rb

cheers
